name: synthetic-medical-core
channels:
  - conda-forge
dependencies:
  - python=3.12.4
  - pip
  - numpy>=1.25
  - pandas>=2.3
  - scipy>=1.13
  - scikit-learn>=1.5
  - matplotlib>=3.8
  - seaborn>=0.13
  - xgboost>=2.0
  - pytorch
  - pip:
      - sdv
      - arfpy
      - joblib
